version: '2'
services:
    chafraterno-app:
        image: chafraterno
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://chafraterno-postgresql:5432/chafraterno
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    chafraterno-postgresql:
        extends:
            file: postgresql.yml
            service: chafraterno-postgresql
