version: '2'
services:
    chafraterno-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/chafraterno/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=chafraterno
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
